version: '3'
services:

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    restart: always
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: INSIDE_KAFKA://0.0.0.0:9093,CONTROLLER://:9094  # KAFKA_LISTENERS parametresi
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: INSIDE_KAFKA://0.0.0.0:9093  # Bu ayar container'ın dinleyeceği portu belirtir
      KAFKA_ADVERTISED_LISTENERS: INSIDE_KAFKA://kafka:9093  # Bu, client'ların kullanacağı adresi belirtir
    ports:
      - "9092:9092"  # Dış port
      - "9093:9093"  # Kafka'nın INSIDE_KAFKA adresi için
    depends_on:
      - zookeeper
    networks:
      - app-network

networks:
  app-network:
    driver: bridge