server:
  address: ${SERVER_PORT:0.0.0.0}
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:airlines}
    username: ${MYSQL_USER:test}
    password: ${MYSQL_PASSWORD:test}
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:mongoadmin}:${MONGO_PASSWORD:secret}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:airlines}?authSource=admin&authMechanism=SCRAM-SHA-1

springdoc:
  packagesToScan: com.sipahi.airlines
  swagger-ui:
    enabled: true
    path: /swagger-ui

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

kafka:
  topic:
    saveFlightAmount: save-flight-amount
    updateFlightAmount: update-flight-amount
  groupId: ${KAFKA_GROUP_ID:airlines-group}
  address: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9093}

elasticsearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}

cache-time:
  flightDetailCacheMinute: ${CACHE_FLIGHT_DETAIL_MINUTE:10}
  aircraftDetailCacheMinute: ${CACHE_AIRCRAFT_DETAIL_MINUTE:20}
  aircraftListCacheMinute: ${CACHE_AIRCRAFT_LIST_MINUTE:20}