server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/airlines
    username: test
    password: test
  data:
    mongodb:
      uri: mongodb://localhost:27017/airlines

springdoc:
  packagesToScan: com.sipahi.airlines
  swagger-ui:
    enabled: true
    path: /swagger-ui

redis:
  host: localhost
  port: 6379

kafka:
  topic:
    saveFlightAmount: save-flight-amount
    updateFlightAmount: update-flight-amount
  groupId: airlines-group
  address: localhost:9093

cache-time:
  flightDetailCacheMinute: 10
  aircraftDetailCacheMinute: 20
  aircraftListCacheMinute: 20